#cloud-config

# Install packages
packages:
  - nano
  - tmux
  - git
  - python3-pip

# Write out config file for email-oauth2-proxy
write_files:
  - path: /tmp/personal.config
    encoding: base64
    content: ${base64encode(email_oauth2_proxy_config)}
    permissions: '0640'
  - path: /tmp/fullchain.pem
    encoding: base64
    content: ${base64encode(cert_fullchain)}
    permissions: '0640'
  - path: /tmp/privkey.pem
    encoding: base64
    content: ${base64encode(cert_privkey)}
    permissions: '0640'

# Run commands
runcmd:
  # Configure timezone (which will be used in email-oauth2-proxy log's timestamps)
  - rm /etc/localtime
  - timedatectl set-timezone ${timezone}
  # Install email-oauth2-proxy
  - sudo -u ec2-user git clone --depth 1 --branch ${email_oauth2_proxy_version} https://github.com/simonrob/email-oauth2-proxy.git /home/ec2-user/email-oauth2-proxy
  - sudo -u ec2-user sed -i 's/^pystray$/pystray==0.18.0/g' /home/ec2-user/email-oauth2-proxy/requirements.txt
  - sudo -u ec2-user python3 -m pip install -r /home/ec2-user/email-oauth2-proxy/requirements.txt
  # Configure email-oauth2-proxy
  - mv /tmp/personal.config /home/ec2-user/email-oauth2-proxy/personal.config
  - mv /tmp/fullchain.pem /home/ec2-user/email-oauth2-proxy/fullchain.pem
  - mv /tmp/privkey.pem /home/ec2-user/email-oauth2-proxy/privkey.pem
  - sed -i "s/{{private_ip}}/$(hostname -I)/g" /home/ec2-user/email-oauth2-proxy/personal.config
  - chown ec2-user:ec2-user /home/ec2-user/email-oauth2-proxy/personal.config
  - chown root:ec2-user /home/ec2-user/email-oauth2-proxy/fullchain.pem
  - chown root:ec2-user /home/ec2-user/email-oauth2-proxy/privkey.pem
  # Command to run:
  #  ssh -L 8080:127.0.0.1:8080 ec2-user@<PUBLIC_IP>
  #     tmux
  #     PYSTRAY_BACKEND=dummy python3 /home/ec2-user/email-oauth2-proxy/emailproxy.py --no-gui --local-server-auth --config-file /home/ec2-user/email-oauth2-proxy/personal.config
